APP_NAME: next
API_KEY: api_key
MASTER_KEY: master_key
DATABASE_URL: postgres://postgres:@localhost/postgres?sslmode=disable
URL_PREFIX: ''
CORS_HOST: '*'

# Auth JWT store setting
TOKEN_STORE:
  EXPIRY: 0
  SECRET: secret

# Auth setting
AUTH:
  AUTH_RECORD_KEYS:
  - - email
  - - username
  CUSTOM_TOKEN_SECRET: ssosecret

# SMS and SMTP provider
NEXMO:
  API_KEY: nexmo_api_key
  API_SECRET: nexmo_api_secret
  FROM: '85212345678'
TWILIO:
  ACCOUNT_SID: twilio_account_sid
  AUTH_TOKEN: twilio_auth_token
  FROM: '+15005550006'
SMTP:
  HOST: smtp.gmail.com
  MODE: tls
  LOGIN: login
  PASSWORD: password
  PORT: 587

# SSO Setting
SSO_SETTING:
  ALLOWED_CALLBACK_URLS:
  - http://127.0.0.1:5000/
  - http://localhost:5000/
  AUTO_LINK_PROVIDER_KEYS:
  - email
  JS_SDK_CDN_URL: http://0.0.0.0:5000/bundle.js
  STATE_JWT_SECRET: ''
  URL_PREFIX: http://127.0.0.1:3001/auth
SSO_CONFIGS:
- CLIENT_ID: id.apps.googleusercontent.com
  CLIENT_SECRET: client_secret
  NAME: google
  SCOPE: email
- CLIENT_ID: ''
  CLIENT_SECRET: ''
  NAME: facebook
  SCOPE: ''
- CLIENT_ID: ''
  CLIENT_SECRET: ''
  NAME: instagram
  SCOPE: ''
- CLIENT_ID: ''
  CLIENT_SECRET: ''
  NAME: linkedin
  SCOPE: ''

USER_AUDIT:
  # user audit trail
  ENABLED: false
  TRAIL_HANDLER_URL: ''
  # password policy
  PW_DIGIT_REQUIRED: false
  PW_EXCLUDED_FIELDS: null
  PW_EXCLUDED_KEYWORDS: null
  PW_EXPIRY_DAYS: 0
  PW_HISTORY_DAYS: 0
  PW_HISTORY_SIZE: 3
  PW_LOWERCASE_REQUIRED: false
  PW_MIN_GUESSABLE_LEVEL: 0
  PW_MIN_LENGTH: 6
  PW_SYMBOL_REQUIRED: false
  PW_UPPERCASE_REQUIRED: false

# User profile store: default JSON or record
USER_PROFILE:
  IMPLEMENTATION: ''
  IMPL_STORE_URL: ''

# User verify
USER_VERIFY:
  REQUIRED: false
  URL_PREFIX: http://localhost:3000
  AUTO_SEND_SIGNUP: false
  AUTO_SEND_UPDATE: false
  AUTO_UPDATE: false
  CRITERIA: ''
  ERROR_HTML_URL: ''
  ERROR_REDIRECT: ''
  KEYS:
  - email
  - phone
  KEY_CONFIGS:
  - CODE_FORMAT: complex
    SUCCESS_HTML_URL: ''
    SUCCESS_REDIRECT: ''
    ERROR_HTML_URL: ''
    ERROR_REDIRECT: http://error-test.com?abc=1&test=abc
    EXPIRY: 3600
    KEY: email
    PROVIDER: smtp
    PROVIDER_CONFIG:
      REPLY_TO: ''
      REPLY_TO_NAME: ''
      SENDER: no-reply@skygeario.com
      SENDER_NAME: Skygear
      SUBJECT: Please verify your email
      HTML_URL: https://skygear-cloud-asset.com/user-verify/email.html
      TEXT_URL: https://skygear-cloud-asset.com/user-verify/email.txt
  - CODE_FORMAT: numeric
    SUCCESS_HTML_URL: ''
    SUCCESS_REDIRECT: ''
    ERROR_HTML_URL: ''
    ERROR_REDIRECT: ''
    EXPIRY: 3600
    KEY: phone
    PROVIDER: nexmo
    PROVIDER_CONFIG:
      HTML_URL: ''
      REPLY_TO: ''
      REPLY_TO_NAME: ''
      SENDER: ''
      SENDER_NAME: ''
      SUBJECT: ''
      TEXT_URL: https://skygear-cloud-asset.com/user-verify/sms.txt

# Forgot password
FORGOT_PASSWORD:
  URL_PREFIX: http://localhost:3000/auth
  APP_NAME: next
  SECURE_MATCH: false
  RESET_URL_LIFE_TIME: 43200
  SENDER: no-reply@skygeario.com
  SENDER_NAME: Skygear
  REPLY_TO: ''
  REPLY_TO_NAME: ''
  SUBJECT: Forgot Password
  EMAIL_HTML_URL: https://skygear-cloud-asset.com/forgot-password/email.html
  EMAIL_TEXT_URL: https://skygear-cloud-asset.com/forgot-password/email.txt
  RESET_HTML_URL: https://skygear-cloud-asset.com/forgot-password/reset.html
  RESET_SUCCESS_HTML_URL: https://skygear-cloud-asset.com/forgot-password/reset-success.html
  SUCCESS_REDIRECT: ''
  RESET_ERROR_HTML_URL: https://skygear-cloud-asset.com/forgot-password/reset-error.html
  ERROR_REDIRECT: ''

# Welcome email
WELCOME_EMAIL:
  ENABLED: false
  URL_PREFIX: ''
  SENDER: no-reply@skygeario.com
  SENDER_NAME: ''
  REPLY_TO: ''
  REPLY_TO_NAME: ''
  SUBJECT: Welcome!
  HTML_URL: ''
  TEXT_URL: ''
