API_KEY: api_key
MASTER_KEY: master_key
CORS_HOST: '*'

# Auth JWT store setting
TOKEN_STORE:
  EXPIRY: 0
  SECRET: secret

# Auth setting
AUTH:
  CUSTOM_TOKEN_SECRET: ssosecret

# SMS and SMTP provider
NEXMO:
  API_KEY: nexmo_api_key
  API_SECRET: nexmo_api_secret
  FROM: '85212345678'
TWILIO:
  ACCOUNT_SID: twilio_account_sid
  AUTH_TOKEN: twilio_auth_token
  FROM: '+15005550006'
SMTP:
  HOST: smtp.gmail.com
  MODE: tls
  LOGIN: login
  PASSWORD: password
  PORT: 587

# SSO Setting
SSO:
  ALLOWED_CALLBACK_URLS:
  - http://127.0.0.1:5000/
  - http://localhost:5000/
  MERGE_USERS_WITH_IDENTICAL_EMAIL: true 
  STATE_JWT_SECRET: '' # default master key
  PROVIDER_CONFIGS:
  - CLIENT_ID: id.apps.googleusercontent.com
    CLIENT_SECRET: client_secret
    NAME: google
    SCOPE: email
  - CLIENT_ID: ''
    CLIENT_SECRET: ''
    NAME: facebook
    SCOPE: ''
  - CLIENT_ID: ''
    CLIENT_SECRET: ''
    NAME: instagram
    SCOPE: ''
  - CLIENT_ID: ''
    CLIENT_SECRET: ''
    NAME: linkedin
    SCOPE: ''

USER_AUDIT:
  # User audit trail
  ENABLED: false
  TRAIL_HANDLER_URL: ''
  # Password policy
  PW_DIGIT_REQUIRED: false
  PW_EXCLUDED_FIELDS: null
  PW_EXCLUDED_KEYWORDS: null
  PW_EXPIRY_DAYS: 0
  PW_HISTORY_DAYS: 0
  PW_HISTORY_SIZE: 3
  PW_LOWERCASE_REQUIRED: false
  PW_MIN_GUESSABLE_LEVEL: 0
  PW_MIN_LENGTH: 6
  PW_SYMBOL_REQUIRED: false
  PW_UPPERCASE_REQUIRED: false

# User verify
USER_VERIFY:
  REQUIRED: false
  AUTO_SEND_SIGNUP: false
  AUTO_SEND_UPDATE: false
  AUTO_UPDATE: false
  CRITERIA: ''
  ERROR_HTML: |-
    <!DOCTYPE html>
    <head>
      <meta name="viewport" content="width=device-width, initial-scale=1">
    </head>
    <p>{{ error }}</p>
  ERROR_REDIRECT: ''
  KEYS:
  - email
  - phone
  KEY_CONFIGS:
  - KEY: email
    CODE_FORMAT: complex
    EXPIRY: 3600
    PROVIDER: smtp
    SUCCESS_HTML: |-
      <!DOCTYPE html>
      <head>
        <meta name="viewport" content="width=device-width, initial-scale=1">
      </head>
      <p>Your account information is verified successfully.</p>
    SUCCESS_REDIRECT: ''
    ERROR_HTML: |-
      <!DOCTYPE html>
      <head>
        <meta name="viewport" content="width=device-width, initial-scale=1">
      </head>
      <p>{{ error }}</p>
    ERROR_REDIRECT: ''
    PROVIDER_CONFIG:
      SENDER: no-reply@skygeario.com
      SENDER_NAME: Skygear
      REPLY_TO: ''
      REPLY_TO_NAME: ''
      SUBJECT: Please verify your email
      EMAIL_HTML: |-
        <p>Dear {{ record_value }},</p>
        
        <p>You received this email because {{ appname }} would like to verify your email address. If you have recently signed up for this app or if you have recently made changes to your account, click the following link:</p>
        <p>{{ link }}</p>
        <p>If you are unsure why you received this email, please ignore this email and you do not need to take any action.</p>
        
        <p>Thanks.</p>
  - KEY: phone
    EXPIRY: 3600
    CODE_FORMAT: numeric
    PROVIDER: nexmo
    SUCCESS_HTML: |-
      <!DOCTYPE html>
      <head>
        <meta name="viewport" content="width=device-width, initial-scale=1">
      </head>
      <p>Your account information is verified successfully.</p>
    SUCCESS_REDIRECT: ''
    ERROR_HTML: |-
      <!DOCTYPE html>
      <head>
        <meta name="viewport" content="width=device-width, initial-scale=1">
      </head>
      <p>{{ error }}</p>
    ERROR_REDIRECT: ''
    PROVIDER_CONFIG:
      SMS_TEXT: 'Your {{ appname }} Verification Code is: {{ code }}'

# Forgot password
FORGOT_PASSWORD:
  APP_NAME: next
  SECURE_MATCH: false
  RESET_URL_LIFE_TIME: 43200
  SENDER: no-reply@skygeario.com
  SENDER_NAME: Skygear
  REPLY_TO: ''
  REPLY_TO_NAME: ''
  SUBJECT: Forgot Password
  EMAIL_HTML: |-
    <p>Dear {{ user.email }},</p>

    <p>
    You received this email because someone tries to reset your account password on {{ appname }}. To reset your account password, click this link\:
    <br/>
    {{ link }}
    <br/>
    If you did not request to reset your account password, Please ignore this email.
    <p/>

    <p>Thanks.<p/>
  RESET_HTML: |-
    <!DOCTYPE html>
    <head>
      <meta name="viewport" content="width=device-width, initial-scale=1">
    </head>
    {% if error %}
    <p>{{ error }}</p>
    {% endif %}
    <form method="POST" action="{{ action_url }}">
      <label for="password">New Password</label>
      <input type="password" name="password"><br>
      <label for="confirm">Confirm Password</label>
      <input type="password" name="confirm"><br>
      <input type="hidden" name="code" value="{{ code }}">
      <input type="hidden" name="user_id" value="{{ user_id }}">
      <input type="hidden" name="expire_at" value="{{ expire_at }}">
      <input type="submit" value="Submit">
    </form>
  RESET_SUCCESS_HTML: |-
    <!DOCTYPE html>
    <head>
      <meta name="viewport" content="width=device-width, initial-scale=1">
    </head>
    <p>Your password is reset successfully.</p>
  SUCCESS_REDIRECT: ''
  RESET_ERROR_HTML: |- 
    <!DOCTYPE html>
    <head>
      <meta name="viewport" content="width=device-width, initial-scale=1">
    </head>
    <p>{{ error }}</p>
  ERROR_REDIRECT: ''

# Welcome email
WELCOME_EMAIL:
  ENABLED: false
  SENDER: no-reply@skygeario.com
  SENDER_NAME: ''
  REPLY_TO: ''
  REPLY_TO_NAME: ''
  SUBJECT: Welcome!
  EMAIL_HTML: |-
    <p>Hello {% if user.name %}{{ user.name }}{% else %}{{ user.email }}{% endif %},</p>

    <p>Welcome to Skygear.</p>

    <p>Thanks.</p>
